### ISSUE TITLE
File Not Found on macOS

### ISSUE THREAD

**Issue by jmaddington** [vndee/llm-sandbox#6]
I downloaded the code_runner_docker.py example and ran it as is.

python 3.11
macOS 15.1

```bash
→ python code_runner_docker.py
Using local Docker context since client is not provided..
Traceback (most recent call last):
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/docker/api/client.py", line 246, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jonathanaddington/Downloads/sandbox/code_runner_docker.py", line 143, in <module>
    run_python_code()
  File "/Users/jonathanaddington/Downloads/sandbox/code_runner_docker.py", line 5, in run_python_code
    with SandboxSession(lang="python", keep_template=True, verbose=True) as session:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/llm_sandbox/session.py", line 43, in __new__
    return SandboxDockerSession(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/llm_sandbox/docker.py", line 65, in __init__
    self.client = docker.from_env()
                  ^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/docker/client.py", line 94, in from_env
    return cls(
           ^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/docker/api/client.py", line 207, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanaddington/Downloads/sandbox/venv/lib/python3.11/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
(venv)
```

to replicate:
```
python3.11 -m venv ./venv
source ./venv/bin/activate
pip install llm-sandbox
wget https://raw.githubusercontent.com/vndee/llm-sandbox/refs/heads/main/examples/code_runner_docker.py
python code_runner_docker.py
```

**Comment by vndee** [comment]
Hey @jmaddington, the error suggests that Docker daemon is not running or accessible on your system.

Before running the example, please ensure that:

1. Docker Desktop is installed and running on your macOS
2. Docker daemon is properly started 
   - You can verify this by running `docker ps` in terminal
   - If you see a similar connection error, try starting Docker Desktop application

If you've confirmed Docker is running and still encounter issues, please check if your user has the necessary permissions to access the Docker socket.

**Comment by vndee** [comment]
I have just figured out the issue, and this command work for me:
```bash
sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock
```

I'll close this issue due to long time inactivity.

**Comment by DominikDary** [comment]
Thank you @vndee , that worked for me as well!
